# Generated by Django 5.1 on 2024-08-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='products',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
